# Generated by Django 3.2.9 on 2022-03-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='jiren.png', null=True, upload_to=''),
        ),
    ]
